### ISSUE TITLE
ordering broke with no reason

### ISSUE THREAD

**Issue by Sonic4Tails** [WiiLink24/food-server#16]
so i was ordering for fun and out nowhere ordering broke trying to use a fresh install and resetting database doesnt have any effect and it stays broken, attached below is the log

127.0.0.1 - - [08/Aug/2022 21:39:12] "POST /nwapi.php HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\purpe\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\purpe\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\purpe\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\purpe\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\purpe\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\purpe\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\purpe\Downloads\food-server-master\food.py", line 115, in error_api
    return action_list[action](request)
  File "C:\Users\purpe\Downloads\food-server-master\helpers.py", line 78, in serialization_wrapper
    returned_value = func(*args, **kwargs)
  File "C:\Users\purpe\Downloads\food-server-master\responses.py", line 476, in basket_add
    order: list = query.basket
AttributeError: 'NoneType' object has no attribute 'basket'

**Comment by lambda-makes-things** [comment]
Now im not super qualified for this, but was ordering working before this broke, or were you ordering for the first time? @Sonic4Tails

**Comment by lambda-makes-things** [comment]
> Now im not super qualified for this, but was ordering working before this broke, or were you ordering for the first time? @Sonic4Tails

actually hold on ima hand this off to @spotlightishere because they are much more qualified than i am lmao

**Comment by Sonic4Tails** [comment]
Yes ordering worked beforeVan: LambdaVerzonden: dinsdag 9 augustus 2022 23:26Aan: WiiLink24/food-serverCC: Sonic4Tails; MentionOnderwerp: Re: [WiiLink24/food-server] ordering broke with no reason (Issue #16) Now im not super qualified for this, but was ordering working before this broke, or were you ordering for the first time? @Sonic4Tailsactually ima hand this off to @spotlightishere because they are much more qualified than i am lmao—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by SketchMaster2001** [comment]
You most likely had your save data removed. When the query returns None, this means that the `zip_code` that your save data contained was not stored in the database. On every new save data creation, we add the `zip_code` to our database.

Please try and delete your save data from Wii System Management and try again.

**Comment by Sonic4Tails** [comment]
That did the trick thank you for your tip!Van: SketchVerzonden: woensdag 10 augustus 2022 13:59Aan: WiiLink24/food-serverCC: Sonic4Tails; MentionOnderwerp: Re: [WiiLink24/food-server] ordering broke with no reason (Issue #16) You most likely had your save data removed. When the query returns None, this means that the zip_code that your save data contained was not stored in the database. On every new save data creation, we add the zip_code to our database.Please try and delete your save data from Wii System Management and try again.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
